# Generated by Django 4.1.5 on 2023-02-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidades', models.PositiveIntegerField()),
                ('credito_requerido', models.IntegerField()),
                ('cantidadmax_estudiantes', models.IntegerField()),
                ('cantidad_estudiantes', models.IntegerField()),
                ('abierta', models.BooleanField(default=False)),
                ('carrera', models.CharField(choices=[('Industrial', 'Ingieneria Industrial'), ('Mecanica', 'Ingieneria Mecanica'), ('Sistemas', 'Ingieneria Sistemas'), ('General', 'General')], max_length=15, verbose_name='Carrera')),
            ],
        ),
    ]
