# Generated by Django 4.1.3 on 2023-02-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
    ]
