# Generated by Django 4.1.6 on 2023-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_registroinscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='registroinscripcion',
            name='materias_ids',
            field=models.ManyToManyField(null=True, to='Academico.materia'),
        ),
    ]
