# Generated by Django 4.1.7 on 2023-03-05 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_alter_registroinscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinscripcion',
            name='materias_ids',
            field=models.ManyToManyField(blank=True, to='Academico.materia'),
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('registro_inscripcion', models.IntegerField()),
                ('cantidad_pago', models.FloatField()),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registroinscripcion',
            name='pago_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.registropago'),
        ),
    ]
