# Generated by Django 4.1.3 on 2023-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0013_remove_usuario_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinscripcion',
            name='hora_apertura',
            field=models.DateField(blank=True, null=True, verbose_name='hora de apertura de inscripcion'),
        ),
        migrations.AlterField(
            model_name='registroinscripcion',
            name='fecha_apertura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de apertura de inscripcion'),
        ),
    ]
