# Generated by Django 4.1.7 on 2023-03-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_registroinscripcion_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinscripcion',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de apertura de inscripcion'),
        ),
    ]
