# Generated by Django 4.1.3 on 2023-04-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0015_alter_registroinscripcion_hora_apertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='banco',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='registropago',
            name='cuenta',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='registropago',
            name='moneda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registropago',
            name='num_referencia',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='registropago',
            name='num_tarjeta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registropago',
            name='remitente_cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registropago',
            name='tlf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
