# Generated by Django 4.1.7 on 2023-04-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0016_registropago_banco_registropago_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='num_referencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
