# Generated by Django 4.1.7 on 2023-04-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0017_alter_registropago_num_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
