# Generated by Django 4.1.5 on 2023-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Especialidad', models.CharField(max_length=100)),
                ('CantidadMax', models.IntegerField()),
                ('Abierta', models.BooleanField(default=False)),
                ('Unidades', models.IntegerField()),
            ],
        ),
    ]
